version: '3'

services:
  neo4j_datastore:
    container_name: neo4j
    image: neo4j:3.4
    restart: unless-stopped
    volumes:
      - ./data/neo4j:/data
      - ./import:/var/lib/neo4j/import
      - ./conf:/var/lib/neo4j/conf
      - ./plugins:/var/lib/neo4j/plugins
      - ./certs:/var/lib/neo4j/certificates
      - ./logs:/var/lib/neo4j/logs
    ports:
      - 7474:7474
      - 7687:7687